apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-application-gitlab
  labels:
    app: will-gitlab
spec:
  project: default
  source:
    repoURL: http://localhost:8181/root/lnemor-will-iot.git #gitlab repo url
    targetRevision: HEAD
    path: app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
