apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: app2-development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: bonita
    spec:
      containers:
      - name: app2
        image: ghcr.io/luthernmr/technical-test-bonita:develop
        envFrom:
        - secretRef:
            name: bonita-secrets
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: 
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---     

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-wildcard-host
spec:
  rules:
  - host: "app2.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80