apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  namespace: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3-container
        image: yeasy/simple-web
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: app3-service
  namespace: app3
spec:
  selector:
    app: app3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---     

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app3-ingress
  namespace: app3
spec:
  rules:
  - host: "app3.com"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app3-service
            port:
              number: 80