apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will-application
  labels:
    app: will
spec:
  project: default
  source:
    repoURL: https://github.com/Luthernmr/lnemor-wil-iot.git
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
