Vagrant.configure("2") do |config|
  # Configuration du nœud maître
  config.vm.box = "centos/7"
  config.vm.box_url = BOX_URL
  config.vm.provision "shell", inline: $DISABLE_FIREWALL_SCRIPT 
  config.vm.define "lnemorS" do |master|
    master.vm.hostname = "lnemorS" 
    master.vm.network "private_network", ip: "192.168.56.110"
    master.vm.synced_folder ".", "/vagrant", type: "virtualbox"
    master.vm.provision "shell", path: "scripts/script.sh", privileged: true
    master.vm.provider "virtualbox" do |vb|
      vb.name = "lnemorS"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end
