Vagrant.configure("2") do |config|
    # Master node configuration
    config.vm.box = "ubuntu/jammy64"
    config.vm.define "lnemorS" do |master|
      master.vm.hostname = "lnemorS" 
      master.vm.network "private_network", ip: "192.168.56.110"
      master.vm.provision "shell", path: "scripts/provision_master.sh", privileged: true
      master.vm.provider "virtualbox" do |vb|
        vb.name = "lnemorS"
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
    # Worker node configuration
    config.vm.box = "ubuntu/jammy64"
    config.vm.define "lnemorSW" do |worker|
      worker.vm.hostname = "lnemorSW" 
      worker.vm.network "private_network", ip: "192.168.56.111"
      worker.vm.provision "shell", path: "scripts/provision_worker.sh", privileged: true
      worker.vm.provider "virtualbox" do |vb|
        vb.name = "lnemorSW"
        vb.memory = "1024"
        vb.cpus = 1
      end
      # Provisionnement pour installer K3s en tant que nœud worker
    end
  end
  
