apiVersion: apps/v1
kind: Deployment
metadata:
  name: will--gitlab-deployment
  labels:
    app: will-gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-gitlab
  template:
    metadata:
      labels:
        app: will-gitlab
    spec:
      containers:
        - name: will-gitlab-container
          image: wil42/playground:v2
          ports:
            - containerPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: will--gitlab-service
  labels:
    app: will-gitlab
spec:
  type: LoadBalancer
  selector:
    app: will-gitlab
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8888
